#!/bin/sh
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --output VGA-1 1366x768

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

clipmenud &
remaps &
sxhkd &
xclip &
picom &
dunst &			# dunst for notifications
dwmblocks &

# disable screensaving
xset -dpms &
xset s off &

# setxkbmap -option caps:escape & # turns caps lock into a aditional escape key

xrdb merge $HOME/.config/Xresources

emacs --daemon &

# wallpaper
nitrogen --restore &
