hack: &hack Hack Nerd Font:pixelsize=10
awesome: &awesome Fonte Awesome 6:pixelsize=10
bg_default: &bg_default {stack: [{background: {color: 458588ff}}, {underline: {size: 4, color: 458588ff}}]}
bar:
  height: 20
  location: top
  font: Fira Code:pixelsize=10
  spacing: 2
  margin: 0
  layer: bottom
  foreground: eeeeeeff
  background: 1d2021ff

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 8
              # default: {string: {text: , font: *hack}}
              conditions:
                id == 1: {string: {text: 1, font: *hack}}  
                id == 2: {string: {text: 2, font: *hack}}  
                id == 3: {string: {text: 3, font: *hack}}  
                id == 4: {string: {text: 4, font: *hack}}  
                id == 5: {string: {text: 5, font: *hack}}  
                id == 6: {string: {text: 6, font: *hack}}  
                id == 7: {string: {text: 7, font: *hack}}  
                id == 8: {string: {text: 8, font: *hack}}  
                id == 9: {string: {text: 9, font: *hack}}  
                id == 10: {string: {text: "", font: *hack}}  
                  #id == 11: {string: {text: "sticky", font: *hack}}  

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied:
                map:
                  <<: *river_base
                  deco: {background: {color: 1d2021ff}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {background: {color: 3c3836ff}}
    - river:
        title: {string: {text: "{title}", max: 30} }
        content: 
                map: 
                    conditions: 
                        ~focused: {empty: {}}
  right:
    #- script:
    #    path: /home/joao/.local/bin/yamusic
    #    args: []
    #    poll-interval: 1
    #    content:
    #      map:
    #        conditions:
    #          sts == "paused": {string: {text: "babidi"}}
    #          sts == "playing": {string: {text: "majinboo"}}
    #    - label:
    #              content: {string: {text: " | " }}
    #    - mem:
    #        interval: 2500
    #        content:
    #          string: {text: "mem: {used:mb}MB/{total:mb}MB"}
    - label:
              content: {string: {text: " | " }}
                #    - pulse:
                #        content:
                #          - map:
                #              conditions:
                #                  sink_muted: {string: {text: "muted", foreground: ff0000ff}}
                #                  online: {string: {text: "vol: {sink_percent}%"}}
                #- pipewire:
                #      content:
                #          - map:
                #                conditions:
                #                      type == "sink":
                #                            map:
                #                                  conditions:
                #                                      muted: {string: {text: "muted", foreground: ff0000ff } }
                #                                      ~muted: {string: {text: "vol: {cubic_volume}%" } }
                #                      type == "source":
                #                            map:
                #                                  conditions:
                #                                      muted: {string: {text: " mic disabled", foreground: ff0000ff} }
                #                                      ~muted: {string: {text: "" } }
    - pipewire:
          content:
              - map:
                    conditions:
                          type == "sink":
                                map:
                                      conditions:
                                          muted: {string: {text: "muted", foreground: ff0000ff } }
                                          ~muted: {string: {text: "vol: {cubic_volume}%" } }
                          type == "source":
                                map:
                                      conditions:
                                          muted: {string: {text: " mic disabled", foreground: ff0000ff} }
                                          ~muted: {string: {text: "" } }
    - label:
              content: {string: {text: " | " }}
    - clock:
            content:
              #- string: {text:  , font: "Font Awesome 6 Free:style=solid:size=10"}
              - string: {text: "date: {date}", right-margin: 5}
              # - string: {text:  , font: "Font Awesome 6 Free:style=solid:size=10"}
              - string: {text: "{time} "}
